apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-n2
  namespace: oai-ran
  annotations:
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Interface.n2
spec:
  config: "{\"cniVersion\":\"0.3.1\",\"plugins\":[{\"type\":\"macvlan\",\"capabilities\":{\"ips\":true},\"master\":\"eno49\",\"mode\":\"bridge\",\"ipam\":{\"type\":\"static\",\"addresses\":[{\"address\":\"172.2.0.2/24\"}]}},{\"type\":\"tuning\",\"capabilities\":{\"mac\":true},\"ipam\":{}}]}"
