apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: cucp-ran-amf-ran
  namespace: oai-ran-cucp
  annotations:
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Dependency.amf
spec:
  config:
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment
    metadata:
      name: amf-ran
      namespace: oai-core
      annotations:
        config.kubernetes.io/index: "0"
        internal.config.kubernetes.io/index: "0"
        internal.config.kubernetes.io/path: amfdeployment.yaml
        internal.kpt.dev/upstream-identifier: workload.nephio.org|NFDeployment|amf-example|amf-example
    spec:
      capacity:
        maxDownlinkThroughput: "0"
        maxSubscribers: 1000
        maxUplinkThroughput: "0"
      interfaces:
      - name: n2
        ipv4:
          address: 172.2.0.1/24
          gateway: ""
        vlanID: 2
      networkInstances:
      - name: vpc-ran
        interfaces:
        - n2
      parametersRefs:
      - name: oai-amf-config
        apiVersion: workload.nephio.org/v1alpha1
        kind: NFConfig
      provider: amf.openairinterface.org
