# Interface-to-NIC mapping for CUUP
# Values are injected via PackageVariant apply-setters
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /interface-setters
  name: interface-setters
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|interface-setters'
data:
  e1-interface: "ens1f1" # kpt-set: ${e1-interface}
  f1u-interface: "ens1f0" # kpt-set: ${f1u-interface}
  n3-interface: "eno49" # kpt-set: ${n3-interface}
