# Interface for N4 (Control Plane - SMF)
apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata: # kpt-merge: /n4
  name: n4
  annotations:
    nephio.org/network-name: n4
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.smf
    specializer.nephio.org/namespace: oai-ran
    internal.kpt.dev/upstream-identifier: 'req.nephio.org|Interface|default|n4'
spec:
  networkInstance:
    name: vpc-internal
  cniType: macvlan
