# Interface for F1c (Control Plane - CUCP to DU)
apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata: # kpt-merge: /f1c
  name: f1c
  annotations:
    nephio.org/network-name: f1
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.cucp
    specializer.nephio.org/namespace: oai-ran
    internal.kpt.dev/upstream-identifier: 'req.nephio.org|Interface|default|f1c'
spec:
  networkInstance:
    name: vpc-cudu-f1
  cniType: macvlan
status:
  ipClaimStatus:
  - prefix: 172.5.1.1/16
    gateway: ""
  - prefix: 172.5.1.3/16
    gateway: ""
  - prefix: 172.5.1.0/16
    gateway: ""
  - prefix: 172.5.1.2/16
    gateway: ""
