# Interface for F1u (User Plane - CUUP to DU)
apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata: # kpt-merge: /f1u
  name: f1u
  annotations:
    nephio.org/network-name: f1
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.cuup
    specializer.nephio.org/namespace: oai-ran
    internal.kpt.dev/upstream-identifier: 'req.nephio.org|Interface|default|f1u'
spec:
  networkInstance:
    name: vpc-cudu-f1
  cniType: macvlan
status:
  ipClaimStatus:
  - prefix: 172.5.1.4/16
    gateway: ""
