# Interface for E1 (CUCP to CUUP)
apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata: # kpt-merge: /e1
  name: e1
  annotations:
    nephio.org/network-name: e1
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.cucp
    specializer.nephio.org/namespace: oai-ran
    internal.kpt.dev/upstream-identifier: 'req.nephio.org|Interface|default|e1'
spec:
  networkInstance:
    name: vpc-cu-e1
  cniType: macvlan
status:
  ipClaimStatus:
  - prefix: 172.4.1.2/16
    gateway: ""
