apiVersion: ipam.resource.nephio.org/v1alpha1
kind: IPClaim
metadata:
  name: cucp-f1c-ipv4
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/for: workload.nephio.org/v1alpha1.NFDeployment.cucp
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Interface.f1c
spec:
  kind: network
  selector:
    matchLabels:
      nephio.org/address-family: ipv4
      nephio.org/cluster-name: ran
      nephio.org/network-name: f1
  networkInstance:
    name: vpc-cudu-f1
status: {prefix: 172.5.1.5/16, gateway: ""}
