apiVersion: ipam.resource.nephio.org/v1alpha1
kind: IPClaim
metadata:
  name: cuup-n3-ipv4
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/for: workload.nephio.org/v1alpha1.NFDeployment.cuup
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Interface.n3
spec:
  kind: network
  selector:
    matchLabels:
      nephio.org/address-family: ipv4
      nephio.org/cluster-name: ran
      nephio.org/network-name: n3
  networkInstance:
    name: vpc-internet
status: {prefix: 172.6.0.1/16, gateway: ""}
