apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: example/cucp-example
  name: cucp-ran
  namespace: oai-ran-cucp
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|example|cucp-example'
spec:
  provider: cucp.openairinterface.org
  parametersRefs:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
    name: cucp-nf-config
  networkInstances:
  - name: vpc-cu-e1
    interfaces:
    - e1
  - name: vpc-cudu-f1
    interfaces:
    - f1c
  - name: vpc-ran
    interfaces:
    - n2
  interfaces:
  - name: e1
    ipv4:
      address: 172.4.1.2/16
      gateway: ""
    vlanID: 3
  - name: f1c
    ipv4:
      address: 172.5.1.2/16
      gateway: ""
    vlanID: 4
  - name: n2
    ipv4:
      address: 172.2.0.0/16
      gateway: ""
    vlanID: 2
