apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: du-ran-cucp-ran
  namespace: oai-ran-du
  annotations:
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Dependency.cucp
spec:
  config:
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment
    metadata:
      name: cucp-ran
      namespace: oai-ran-cucp
      annotations:
        config.kubernetes.io/index: "0"
        internal.config.kubernetes.io/index: "0"
        internal.config.kubernetes.io/path: cucpdeployment.yaml
        internal.kpt.dev/upstream-identifier: workload.nephio.org|NFDeployment|example|cucp-example
    spec:
      interfaces:
      - name: e1
        ipv4:
          address: 172.4.1.2/16
          gateway: ""
        vlanID: 3
      - name: f1c
        ipv4:
          address: 172.5.1.2/16
          gateway: ""
        vlanID: 4
      - name: n2
        ipv4:
          address: 172.2.0.0/16
          gateway: ""
        vlanID: 2
      networkInstances:
      - name: vpc-cu-e1
        interfaces:
        - e1
      - name: vpc-cudu-f1
        interfaces:
        - f1c
      - name: vpc-ran
        interfaces:
        - n2
      parametersRefs:
      - name: cucp-nf-config
        apiVersion: workload.nephio.org/v1alpha1
        kind: NFConfig
      - name: cucp-ran-amf-ran
        apiVersion: ref.nephio.org/v1alpha1
        kind: Config
      provider: cucp.openairinterface.org
